# Site settings
title: renemilk
description: ''
url: 'http://milk.pm'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'René Milk'
  email: rene@milk.pm
  twitter_username: rene_milk
  facebook_username: renemilk
  github_username:  renemilk
  linkedin_username:  renemilk
  stackoverflow_id: 2290151

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
