baseURL = 'https://rene.fritze.me/'
languageCode = 'en-us'
title = 'rene.fritze.me'
# theme = "hugo-theme-terminal"
paginate = 5

[params]
  # this controls what's listed at '/'
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

paginate = 5


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "renefritze"
  site = ""

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'

[languages]
  [languages.en]
    title = "rene.fritze.me"
    subtitle = "My personal blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "rene.fritze.me"
      logoHomeLink = "/posts"


    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"

#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
#      [[languages.en.menu.main]]
#        identifier = "showcase"
#        name = "Showcase"
#        url = "/showcase"
